version: "3.9"

services:
  db:
    container_name: "board-db"
    image: mongo:6-jammy
    ports:
      - "27017:27017"
  web:
    container_name: "board-web"
    build: .
    ports:
      - "80:3000"
    depends_on:
      - db
